apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-xcbpjsme
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/sjmrhtap/go-xcbpjsme:ff7283450bd453cd7754b6d081b73b31988ba3df
          name: container-image
